set -g mouse on

set -g default-terminal "screen-256color"

set -g history-limit 10000

set -g base-index 1
set -g pane-base-index 1
setw -g pane-base-index 1
set -g renumber-windows on 

setw -g mode-keys vi

set -sg escape-time 0

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.tmux.conf \; display "Config Reloaded!!"

bind v split-window -h -c '#{pane_current_path}'
bind h split-window -v -c '#{pane_current_path}'
unbind '"'
unbind %

bind c new-window -c '#{pane_current_path}'

set -g status-position top

set -g status-bg color234
set -g status-fg color137
set -g status-right '#[fg=color233,bg=color241,bold] %d/%m #[fg=color233,bf=color245,bold] %H:%M:%S '
set -g status-right-length 50
setw -g window-status-current-format ' #I#[fg=color250]:#[fg=color255]#W#[fg=color50]#F '
setw -g window-status-format ' #I#[fg=color237]:#[fg=color250]#W#[fg=color244]#F '

set-option -sa terminal-overrides ";xterm*:Tc"

bind k kill-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g  @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
